import type { Metadata } from "next";
import localFont from "next/font/local";
import { CartProvider } from "@/lib/cart-context";
import { Providers } from "@/components/providers";
import { ConditionalNavbarFooter } from "@/components/ConditionalNavbarFooter";
import { PageTransition } from "./components/PageTransition";
import "./globals.css";

const lineSeedSansTH = localFont({
  src: [
    { path: "../lib/font/LINESeedSansTH_W_Th.woff", weight: "100" },
    { path: "../lib/font/LINESeedSansTH_W_Rg.woff", weight: "400" },
    { path: "../lib/font/LINESeedSansTH_W_Bd.woff", weight: "700" },
    { path: "../lib/font/LINESeedSansTH_W_XBd.woff", weight: "800" },
    { path: "../lib/font/LINESeedSansTH_W_He.woff", weight: "900" },
  ],
  variable: "--font-line-seed-sans-th",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className={`${lineSeedSansTH.variable} font-sans antialiased flex flex-col min-h-screen`}>
        <Providers>
          <CartProvider>
            <ConditionalNavbarFooter>
              <main className="flex-1">
                <PageTransition>{children}</PageTransition>
              </main>
            </ConditionalNavbarFooter>
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
